#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e




printf "⏳ Provisionamento dos dispositivos "


#
# Create a service groups for all UltraLight IoT devices
#

curl -s -o /dev/null -X POST \
  "http://iot-agent:$IOTA_NORTH_PORT/iot/services" \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: Fundacentro' \
  -H 'fiware-servicepath: /' \
  -d '{
 "services": [
   {
     "apikey":      "19662024",
     "cbroker":     "'"http://orion:$ORION_PORT"'",
     "entity_type": "MeteorStation",
     "resource":    "/iot/d",
     "protocol":    "PDI-IoTA-UltraLight",
     "transport":   "HTTP",
     "timezone":    "America/SaoPaulo",
     "attributes": [
       { "object_id": "c", "name":"count", "type":"Integer"}
      ],
      "static_attributes": [
          {"name": "category", "type":"Text", "value": ["sensor"]},
          {"name": "function", "type": "Text", "value":["sensing"]},
          {"name": "supportedProtocol", "type": "Text", "value": ["ul20"]}
      ]
   }
 ]
}'

####################################################
#
# Provisionando os sensores do Rasp no Datacenter
#


# Sensor de temperatura: 03303
# Sensor de umidade: 03304
# Presença (movimento): 03302
# Concentração de particulas (detector de fumaça): 03325

# 1 sensor de temperatura, 1 sensor de umidade, 1 sensor de presença, 1 sensor de fumaça

curl -s -o /dev/null -X POST \
  "http://iot-agent:$IOTA_NORTH_PORT/iot/devices" \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: Fundacentro' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "b827eb00f6d0",
     "entity_name": "b827eb00f6d0",
     "entity_type": "Raspberry",
     "commands": [
         {"name": "033030", "type": "command"},
	 {"name": "033040", "type": "command"},
	 {"name": "033020", "type": "command"},
	 {"name": "033250", "type": "command"},
	 {"name": "033110", "type": "command"},
	 {"name": "033111", "type": "command"}
     ],
     "attributes": [
         {"object_id": "033030", "name": "033030", "type": "actual_temp"},
	 {"object_id": "033040", "name": "033040", "type": "actual_umid"},
         {"object_id": "033020", "name": "033020", "type": "actual_presence"},
	 {"object_id": "033250", "name": "033250", "type": "actual_smoke"},
     ],
     "static_attributes": [
         {"name": "FdctSensors", "type": "Relationship", "value": "FdctDatacenter"}
     ]
   }
  ]
}
'

echo -e " \033[1;32mdone\033[0m"
