# Mosquitto MQTT Broker — FdctMonSys
# Rede interna, sem TLS, sem autenticação (acesso restrito à LAN)

listener 1883
allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true
